trigger:
- master
pool:
  vmImage: 'ubuntu-latest'



- script: |
    echo "Building the Java calculator application"
    ./mvnw clean install  # If you use Maven, adjust for Gradle if that's your build tool
    - script: |
    sudo apt-get update
    sudo apt-get install openjdk-11-jdk -y  # Or any version you prefer
    java -version
  displayName: 'Install Java and Check Version'

  displayName: 'Build Java calculator App'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'  
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'