trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Install OpenJDK 11
  - script: |
      sudo apt-get update
      sudo apt-get install openjdk-11-jdk -y
      java -version  # Verify the Java version after installation
    displayName: 'Install Java OpenJDK 11'

  # Build the Java application using Maven (or Gradle if preferred)
  - script: |
      echo "Building the Java calculator application"
      ./mvnw clean install  # Use `./gradlew build` if using Gradle
    displayName: 'Build Java calculator App'

  # Copy generated JAR files to the artifact staging directory
  - task: CopyFiles@2
    inputs:
      contents: '**/*.jar'  # Assuming the build produces JAR files
      targetFolder: '$(Build.ArtifactStagingDirectory)'  # Correct path to artifact staging directory

  # Publish the build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'  # Path to the staged artifacts
      artifactName: 'drop'  # Artifact name, can be customized

