trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
  inputs:
    versionSpec: '21.0.5'  
    jdkArchitecture: 'x64'

- script: |
    - script: |
    sudo apt-get update
    sudo apt-get install openjdk-11-jdk -y  # Or any version you prefer
    java -version
  displayName: 'Install Java and Check Version'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'  
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'

