trigger:
- master
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseJavaToolInstaller@1
  inputs:
    versionSpec: '21.0.5'  # You can specify the desired Java version, like 11 or 17
    jdkArchitecture: 'x64'

- script: |
    echo "Building the Java calculator application"
    ./mvnw clean install  # If you use Maven, adjust for Gradle if that's your build tool
  displayName: 'Build Java calculator App'

- task: CopyFiles@2
  inputs:
    contents: '**/*.jar'  
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'